# SPDX-FileCopyrightText: © 2026 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: CC-BY-4.0

name: Publish Slides

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      # Install Fira Code and Fira Go fonts
      - name: Download and install Fira Code Release
        run: |
          URL="https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip"
          curl -L $URL -o firacode.zip
          unzip firacode.zip -d ./firacode
          mv ./firacode/ttf/*.ttf /usr/share/fonts/
      - name: Download and install Fira Go Release
        run: |
          URL="https://github.com/bBoxType/FiraGO/releases/download/1.000/bBoxType_FiraGO_1000.zip"
          curl -L $URL -o firago.zip
          unzip firago.zip -d ./firago
          mv ./firago/bBoxType_FiraGO_1000/FiraGO_TTF/*/*.ttf /usr/share/fonts/

      - name: Install Typst 0.14.2
        uses: typst-community/setup-typst@v5
        with:
          typst-version: 0.14.2

      - name: Compile slides
        run: typst compile slides/slides.typ slides.pdf

      - name: Upload slides artifact
        uses: actions/upload-artifact@v7
        with:
          name: slides
          path: slides.pdf

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download slides artifact
        uses: actions/download-artifact@v8
        with:
          name: slides

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          files: slides.pdf
